project/SmartSuperHero/urls.py
from django.urls import path

from SmartSuperHero.views import SuperHeroListView, PatientCreateView, PatientDetail, AddQuestion, CaptureView

app_name = "SmartSuperHero"

urlpatterns = [
    path('', SuperHeroListView, name="list"),
    path('add/', PatientCreateView.as_view(), name="add"),
    path('details/<int:pk>/', PatientDetail, name="detail"),
    path('add/question/<int:pk>/', AddQuestion.as_view(), name="question"),
    path('capture/', CaptureView.as_view(), name="capture"),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("SmartSuperHero.urls")),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

]

project/SmartSuperHero/models.py
import datetime

from django.db import models


# Create your models here.


class Doctor(models.Model):
    first_name = models.CharField(max_length=300)
    last_name = models.CharField(max_length=300)
    license_id = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name


class Patient(models.Model):
    first_name = models.CharField(max_length=300)
    last_name = models.CharField(max_length=300)
    patient_id = models.CharField(max_length=300)
    diagnosis = models.CharField(max_length=300)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, )
    birthday = models.CharField(max_length=100)
    parent_fullname = models.CharField(max_length=300)

    def __str__(self):
        return self.first_name


class GenericQuestion(models.Model):
    question = models.CharField(max_length=300)
    keyword = models.CharField(max_length=100)

    def __str__(self):
        return self.question


class Question(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=300)

    def __str__(self):
        return f"question: {self.question}  answer{self.answer}"


class Report(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    report_date = models.DateField(default=datetime.date.today)
    report_content = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"report for {self.patient.first_name} at {self.report_date}"

project/SmartSuperHero/views.py
import subprocess

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView

from SmartSuperHero.models import Patient, Doctor, Report, Question


@login_required
def SuperHeroListView(request):
    m_filter = Patient.objects.filter(doctor__first_name=request.user)

    return render(request, "../templates/SmartSuperHero/patient_list.html", {
        'object_list': m_filter
    })


@login_required
def PatientDetail(requst, pk):
    m_filter = Report.objects.filter(patient__pk=pk)
    my_pk = 0
    if m_filter.count() != 0:
        my_pk = m_filter[0].patient.pk
    return render(requst, '../templates/SmartSuperHero/patient_detail.html', {
        'reports': m_filter,
        'first': my_pk,
    })


class AddQuestion(LoginRequiredMixin, CreateView):
    model = Question
    template_name = '../templates/SmartSuperHero/question_form.html'
    fields = (
        'question',
    )


    def dispatch(self, request, *args, **kwargs):
        self.patient = get_object_or_404(Patient, pk=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.patient = self.patient
        form.instance.answer = ""
        return super().form_valid(form)


class PatientCreateView(LoginRequiredMixin, CreateView):
    model = Patient
    template_name = "../templates/SmartSuperHero/t1.html"
    fields = (
        'first_name',
        'last_name',
        'patient_id',
        'diagnosis',
        'birthday',
        'parent_fullname',
    )
    success_url = reverse_lazy("SmartSuperHero:list")

    def form_valid(self, form):
        form.instance.doctor = Doctor.objects.filter(first_name=self.request.user)[0]
        return super().form_valid(form)


class CaptureView(LoginRequiredMixin, View):

    def post(self):
        subprocess.run("python FacialRecognition/01_face_dataset.py 1")
        return redirect(reverse_lazy("SmartSuperHero:list",))

project/SmartSuperHero/templates/SmartSuperHero/patient_detail.html
{% extends "base.html" %}

{% block title %}
    detail
{% endblock %}

{% block content %}
    <h1 class="text-center">Patient detail !!!</h1>
    <br>
    <div class="container">
        <div class="row">
            <div class="col col-sm-4 text-center">
                <a class="btn btn-primary" href="{% url "SmartSuperHero:question" first %}"> Add question</a>
            </div>
            <div class="col col-sm-4 text-center">
                <button class="btn btn-primary"> Get feedback</button>
            </div>
            <div class="col col-sm-4 text-center">
                <button class="btn btn-primary"> Add report</button>
            </div>

        </div>
    </div>
    <br>
    <div>


        <table class="table table-hover">
            <tr>
                <th>id</th>
                <th>date</th>
                <th>content</th>
            </tr>
            {% for object in reports %}


                <tr>
                    <td>
                        {{ object.id }}
                    </td>
                    <td>
                        {{ object.report_date }}

                    </td>
                    <td>
                        <p>
                            {{ object.report_content }}

                        </p>
                    </td>

                </tr>

            {% endfor %}
        </table>
        <div class="container">
            <div class="row">

                <div class="text-center">
                    <a class="btn btn-danger" href="{% url "SmartSuperHero:list" %}"> Bsack </a>
                </div>

            </div>

        </div>

    </div>
    <br>
    <form action="{% url "SmartSuperHero:capture"  %}" method="post">
    {% csrf_token %}
        <button id="capture" class="btn btn-danger">Capture</button>
    </form>

{% endblock %}

project/SmartSuperHero/templates/SmartSuperHero/patient_list.html
{% extends "base.html" %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1 class="text-center">Patient list !!!</h1>

    {#    <p><a class="btn btn-primary" href="{% url "expenses:create" %}">Create new#}
    {#        expense</a></p>#}

    <div>
        <table class="table table-hover">
            <tr>
                <th>first name</th>
                <th>last name</th>
                <th>id</th>
                <th>diagnosis</th>
                <th>birthday</th>
            </tr>
            {% for object in object_list %}


                <tr>
                    {#                <td>#}
                    {#                    <a href="{% url "expenses:detail" object.id %}">#}
                    {#                        #{{ object.id }}#}
                    {#                    </a>#}
                    {#                </td>#}
                    <td>
                        <a href="{% url "SmartSuperHero:detail" object.id %}">

                            {{ object.first_name }}
                        </a>
                    </td>
                    <td>
                        {{ object.last_name }}
                    </td>
                    <td>
                        {{ object.patient_id }}
                    </td>
                    <td>
                        {{ object.diagnosis }}
                    </td>
                    <td>
                        {{ object.birthday }}
                    </td>
                </tr>

            {% endfor %}
        </table>

        <a class="btn btn-danger btn-lg" href="{% url "SmartSuperHero:add" %}">ADD</a>
    </div>

{% endblock %}

project/SmartSuperHero/templates/SmartSuperHero/question_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}
    question
{% endblock %}

{% block content %}
    <h1>Add question for patient {{ view.patient }}!!!</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn btn-primary"> Submit </button>

                </div>
            </div>
        </div>
    </form>
{% endblock %}

project/SmartSuperHero/templates/SmartSuperHero/t1.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block title %}
    Home
{% endblock %}

{% block content %}

    <br>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <button type="submit" class="btn btn-primary"> HERE</button>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

project/SmartSuperHero/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.css" %}"/>


    <title>
        {% block title %}
            DEFAULT TITLE
        {% endblock %}
    </title>
</head>
<body>

<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand align-self-center" href="#">Super Hero</a>
    {% if user.is_authenticated %}
        <a href="{% url "logout" %}">
            {{ user }} | Logout
        </a>
    {% else %}
        <a href="{% url "login" %}">
            Login
        </a>
    {% endif %}
</nav>

<div class="container-fluid">
    {% block content %}
        DEFAULT CONTENT
    {% endblock %}
</div>

</body>
</html>